language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx-2

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

script: bundle exec rake test
